spring.application.name=demo

ai.ollama.base-url=http://localhost:11434
ai.ollama.chat-model=phi
ai.ollama.embedding-model=nomic-embed-text
ai.ollama.timeout-seconds=120

ai.qdrant.host=localhost
ai.qdrant.grpc-port=6334
ai.qdrant.collection-name=docs
